name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows, os: windows-latest }
        - { name: Linux-x86_64,   os: ubuntu-22.04-x86_64, flags: -GNinja }
        - { name: Linux-arm64,   os: ubuntu-22.04-arm64, flags: -GNinja }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Setup Linux dependencies
      if: startsWith(runner.os, 'Linux')
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build libgl1-mesa-dev libglu1-mesa-dev
    - name: Get sdl12-compat sources
      uses: actions/checkout@v3
    - name: Get SDL2 headers
      uses: actions/checkout@v3
      with:
        repository: libsdl-org/SDL
        ref: SDL2
        path: SDL2
    - name: Configure CMake
      run: cmake -DSDL2_INCLUDE_DIR="${{ github.workspace }}/SDL2/include" -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/

